name: "Mobile System 7 Developer Blog"
description: ""

url: "https://developers.mobilesystem7.com"

markdown: rdiscount
permalink: pretty
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/post/:title
